name: recipys
channels:
  - conda-forge
  - anaconda
dependencies:
  - black=22.10.0
  - coverage=6.5.0
  - flake8=5.0.4
  - numpy=1.23.4
  - pandas=1.5.1
  - pytest=7.2.0
  - tqdm=4.64.1
  - scikit-learn=1.1.3


